/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    CVObject: typeof import('./components/CVObject.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    MacOSHeader: typeof import('./components/MacOSHeader.vue')['default']
    MyTerminal: typeof import('./components/MyTerminal.vue')['default']
    ProjectCard: typeof import('./components/ProjectCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
